require:
  - rubocop/require_tools
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.0
  SuggestExtensions: false
  NewCops: enable
  UseCache: false
  Exclude:
    - "vendor/**/*"

Gemspec/DevelopmentDependencies:
  Enabled: true
  EnforcedStyle: Gemfile

Layout/LineLength:
  Max: 180

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "*.gemspec"

Metrics/ClassLength:
  Max: 320

Metrics/MethodLength:
  Enabled: false

Naming/FileName:
  Exclude:
    - "Gemfile"
    - "Rakefile"
    - "fastlane/Fastfile"
    - "fastlane/Pluginfile"
    - "*.gemspec"

Naming/PredicateName:
  Enabled: false

Require/MissingRequireStatement:
  Exclude:
    - "lib/fastlane/plugin/teams_bot/actions/**/*"
    - "spec/**/*"

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false
